# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
  export ZSH=/home/mstefank/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="maranCustom"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  mvn
  docker
  docker-compose
  gradle
  globalias
  zsh-autosuggestions
  gh
)

source $ZSH/oh-my-zsh.sh

# User configuration

# Custom ENV
. ~/.env

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

alias zshconfig='vim ~/.zshrc'
alias i3config='vim ~/.config/i3/config'
alias t=/home/mstefank/apps/todo.txt_cli-2.11.0/todo.sh

# java
alias j8='jenv global 1.8.0.265'
alias j9='jenv global 9'
alias j10='jenv global 10.0.2'
alias j11='jenv global 11.0.8'
alias j12='jenv global 12.0.2'
alias j13='jenv global 13.0.2'
alias j14='jenv global 14.0.2'
alias j15='jenv global 15-ea'
alias jj='java -jar'
alias jv='java -version'

# git
alias glg='git lg'
alias glgi='git lgi'
alias gacane='git acane'
alias ggpushf='ggpush -f'
alias gupull='git pull upstream $(git_current_branch)'
alias gplu='git pull upstream' 
alias gwip='git wip'
alias grwip='git reset --soft @~ && git reset'
alias gch='git checkout HEAD --'
alias gfpr='git fpr'
alias gcl='hub clone'
alias gra='hub remote add'
alias gpr='gh pr'
alias gprc='gh pr checkout'

# mvn
alias mi='mvn install'
alias mci='mvn clean install'
alias mcif='mvn clean install -DskipTests -Denforcer.skip -Dcheckstyle.skip -Dmaven.javadoc.skip'
alias mcit='mvn clean install -DskipTests'
alias mcie='mvn clean install -fae'
alias mct='mvn clean test'
alias mcqd='mvn clean compile quarkus:dev'
alias mcin='mvn clean install -Pnative'
alias mp='mvn package'
alias mcp='mvn clean package'
alias mcpt='mvn clean package -DskipTests'
alias mt='mvn test'
alias 🤘="mvn clean compile quarkus:dev"
alias mdt='mvn dependency:tree'

# idea
alias i='idea pom.xml'

# grep
alias grep='grep --color=auto'
alias ggrep='grep --exclude-dir={.bzr,CVS,.git,.hg,.svn}'
alias -g G='| grep '
alias -g Gi='| grep '

# quarkus
alias qa='qa() { mvn quarkus:add-extension -Dextensions="$1" };qa'
alias qd='mvn clean compile quarkus:dev'
alias ql='mvn quarkus:list-extensions'

# docker
alias d='docker'
alias doc='docker-compose'

# other
alias cs='cleanServer'
alias background='f(){ "$@" > /dev/null 2>&1 & disown };f'

# invert Ctrl+Space
# just reference, leaves ^@ after expansion
#bindkey -M emacs "^ " globalias
#bindkey -M viins "^ " globalias
#bindkey -M emacs " " magic-space
#bindkey -M viins " " magic-space

function my-expand() zle _expand_alias && zle expand-word
zle -N my-expand
bindkey -M emacs "^ " my-expand
bindkey -M viins "^ " my-expand
bindkey -M emacs " " magic-space
bindkey -M viins " " magic-space

#
unsetopt share_history

# JWT

decode_base64_url() {
  local len=$((${#1} % 4))
  local result="$1"
  if [ $len -eq 2 ]; then result="$1"'=='
  elif [ $len -eq 3 ]; then result="$1"'='
  fi
  echo "$result" | tr '_-' '/+' | openssl enc -d -base64
}

decode_jwt(){
   decode_base64_url $(echo -n $2 | cut -d "." -f $1) | jq .
}

# Decode JWT header
alias jwth="decode_jwt 1"

# Decode JWT Payload
alias jwtp="decode_jwt 2"

# jenv
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

# jabba
[ -s "/home/mstefank/.jabba/jabba.sh" ] && source "/home/mstefank/.jabba/jabba.sh"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/mstefank/apps/google-cloud-sdk/path.zsh.inc' ]; then . '/home/mstefank/apps/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/mstefank/apps/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/mstefank/apps/google-cloud-sdk/completion.zsh.inc'; fi

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/mstefank/.sdkman"
[[ -s "/home/mstefank/.sdkman/bin/sdkman-init.sh" ]] && source "/home/mstefank/.sdkman/bin/sdkman-init.sh"


