# autogenerated by txs
#include:lineno
#include:varioref
\LineWithPage{arg1}#S
\filedate#S
\reftextafter#S
\reftextbefore#S
\reftextfaceafter#S
\reftextfacebefore#S
\reftextfaraway#S
\vpagelineref{arg1}#S
\fileversion#S
\vpagelineref #S
