# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

JAVA_HOME=
M2_HOME=
MAVEN_HOME=$M2_HOME
export TODOTXT_SORT_COMMAND="sort -rf -k2"

